name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v4.6.0
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t juanpablo24/restaurant-aws-ec2 .
      - name: Publish image to Docker Hub
        run: docker push juanpablo24/restaurant-aws-ec2:latest

  deploy:
    needs: build
    runs-on: [restaurant-aws-ec2]
    steps:
      - name: Pull image from docker hub
        run: docker pull juanpablo24/restaurant-aws-ec2:latest
      - name: Delete old container
        run: docker rm - f restaurant-aws-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name restaurant-aws-container juanpablo24/restaurant-aws-ec2
